FROM python:3.10-slim
WORKDIR /app

# 1) Installer les dépendances
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 2) Copier le code FastAPI
COPY src/ ./src/

# 3) Copier le modèle entraîné à la racine /app
COPY src/model.pth ./model.pth

EXPOSE 8000

# 4) Variables d’env pour app.py (chemins internes au conteneur)
ENV MODEL_PATH="model.pth"
ENV RAW_DIR="data/raw"

# 5) Lancement de l’API
CMD ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "8000"]
